<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;


class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('countries')->insert( ['country_name'=>'Afghanistan','country_code'=>'AF','International_dialing'=>'+93','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Albania','country_code'=>'AL','International_dialing'=>'+355','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Algeria','country_code'=>'DZ','International_dialing'=>'+213','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'American Samoa','country_code'=>'AS','International_dialing'=>'+1-684','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Andorra, Principality of','country_code'=>'AD','International_dialing'=>'+376','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Angola','country_code'=>'AO','International_dialing'=>'+244','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Anguilla','country_code'=>'AI','International_dialing'=>'+1-264','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Antarctica','country_code'=>'AQ','International_dialing'=>'+672','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Antigua and Barbuda','country_code'=>'AG','International_dialing'=>'+1-268','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Argentina','country_code'=>'AR','International_dialing'=>'+54','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Armenia','country_code'=>'AM','International_dialing'=>'+374','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Aruba','country_code'=>'AW','International_dialing'=>'+297','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Australia','country_code'=>'AU','International_dialing'=>'+61','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Austria','country_code'=>'AT','International_dialing'=>'+43','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Azerbaijan or Azerbaidjan (Former Azerbaijan Soviet Socialist Republic)','country_code'=>'AZ','International_dialing'=>'+994','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Bahamas, Commonwealth of The','country_code'=>'BS','International_dialing'=>'+1-242','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Bahrain, Kingdom of (Former Dilmun)','country_code'=>'BH','International_dialing'=>'+973','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Bangladesh','country_code'=>'BD','International_dialing'=>'+880','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Barbados','country_code'=>'BB','International_dialing'=>'+1-246','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Belarus','country_code'=>'BY','International_dialing'=>'+375','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Belgium','country_code'=>'BE','International_dialing'=>'+32','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Belize','country_code'=>'BZ','International_dialing'=>'+501','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Benin','country_code'=>'BJ','International_dialing'=>'+229','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Bermuda','country_code'=>'BM','International_dialing'=>'+1-441','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Bhutan, Kingdom of','country_code'=>'BT','International_dialing'=>'+975','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Bolivia','country_code'=>'BO','International_dialing'=>'+591','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Bosnia and Herzegovina','country_code'=>'BA','International_dialing'=>'+387','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Botswana','country_code'=>'BW','International_dialing'=>'+267','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Bouvet Island (Territory of Norway)','country_code'=>'BV','International_dialing'=>'+x','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Brazil','country_code'=>'BR','International_dialing'=>'+55','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'British Indian Ocean Territory (BIOT)','country_code'=>'IO','International_dialing'=>'+x','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Brunei','country_code'=>'BN','International_dialing'=>'+673','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Bulgaria','country_code'=>'BG','International_dialing'=>'+359','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Burkina Faso (Former Upper Volta)','country_code'=>'BF','International_dialing'=>'+226','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Burundi','country_code'=>'BI','International_dialing'=>'+257','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Cambodia, Kingdom of (Former Khmer Republic, Kampuchea Republic)','country_code'=>'KH','International_dialing'=>'+855','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Cameroon','country_code'=>'CM','International_dialing'=>'+237','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Canada','country_code'=>'CA','International_dialing'=>'+1','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Cape Verde','country_code'=>'CV','International_dialing'=>'+238','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Cayman Islands','country_code'=>'KY','International_dialing'=>'+1-345','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Central African Republic','country_code'=>'CF','International_dialing'=>'+236','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Chad','country_code'=>'TD','International_dialing'=>'+235','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Chile','country_code'=>'CL','International_dialing'=>'+56','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'China','country_code'=>'CN','International_dialing'=>'+86','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Christmas Island','country_code'=>'CX','International_dialing'=>'+53','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Cocos (Keeling) Islands','country_code'=>'CC','International_dialing'=>'+61','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Colombia','country_code'=>'CO','International_dialing'=>'+57','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Comoros, Union of the','country_code'=>'KM','International_dialing'=>'+269','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Congo, Democratic Republic of the (Former Zaire)','country_code'=>'CD','International_dialing'=>'+243','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Congo, Republic of the','country_code'=>'CG','International_dialing'=>'+242','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Cook Islands','country_code'=>'CK','International_dialing'=>'+682','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Costa Rica','country_code'=>'CR','International_dialing'=>'+506','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Cote D\'Ivoire (Former Ivory Coast)','country_code'=>'CI','International_dialing'=>'+225','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Croatia (Hrvatska)','country_code'=>'HR','International_dialing'=>'+385','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Cuba','country_code'=>'CU','International_dialing'=>'+53','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Cyprus','country_code'=>'CY','International_dialing'=>'+357','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Czech Republic','country_code'=>'CZ','International_dialing'=>'+420','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Czechoslavakia (Former) See CZ Czech Republic or Slovakia','country_code'=>'CS','International_dialing'=>'+x','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Denmark','country_code'=>'DK','International_dialing'=>'+45','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Djibouti','country_code'=>'DJ','International_dialing'=>'+253','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Dominica','country_code'=>'DM','International_dialing'=>'+1-767','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Dominican Republic','country_code'=>'DO','International_dialing'=>'+1-809 and +1-829  ','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'East Timor','country_code'=>'TP','International_dialing'=>'+670','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Ecuador','country_code'=>'EC','International_dialing'=>'+593 ','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Egypt','country_code'=>'EG','International_dialing'=>'+20','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'El Salvador','country_code'=>'SV','International_dialing'=>'+503','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Equatorial Guinea (Former Spanish Guinea)','country_code'=>'GQ','International_dialing'=>'+240','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Eritrea','country_code'=>'ER','International_dialing'=>'+291','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Estonia','country_code'=>'EE','International_dialing'=>'+372','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Ethiopia','country_code'=>'ET','International_dialing'=>'+251','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Falkland Islands','country_code'=>'FK','International_dialing'=>'+500','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Faroe Islands','country_code'=>'FO','International_dialing'=>'+298','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Fiji','country_code'=>'FJ','International_dialing'=>'+679','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Finland','country_code'=>'FI','International_dialing'=>'+358','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'France','country_code'=>'FR','International_dialing'=>'+33','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'French Guiana or French Guyana','country_code'=>'GF','International_dialing'=>'+594','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'French Polynesia (Former French Colony of Oceania)','country_code'=>'PF','International_dialing'=>'+689','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'French Southern Territories and Antarctic Lands','country_code'=>'TF','International_dialing'=>'+x','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Gabon','country_code'=>'GA','International_dialing'=>'+241','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Gambia, The','country_code'=>'GM','International_dialing'=>'+220','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Georgia','country_code'=>'GE','International_dialing'=>'+995','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Germany','country_code'=>'DE','International_dialing'=>'+49','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Ghana (Former Gold Coast)','country_code'=>'GH','International_dialing'=>'+233','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Gibraltar','country_code'=>'GI','International_dialing'=>'+350','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        // DB::table('countries')->insert( ['country_name'=>'United Kingdom','country_code'=>'GB','International_dialing'=>'+44','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Greece','country_code'=>'GR','International_dialing'=>'+30','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Greenland','country_code'=>'GL','International_dialing'=>'+299','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Grenada','country_code'=>'GD','International_dialing'=>'+1-473','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Guadeloupe','country_code'=>'GP','International_dialing'=>'+590','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Guam','country_code'=>'GU','International_dialing'=>'+1-671','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Guatemala','country_code'=>'GT','International_dialing'=>'+502','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Guinea','country_code'=>'GN','International_dialing'=>'+224','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Guinea-Bissau','country_code'=>'GW','International_dialing'=>'+245','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Guyana','country_code'=>'GY','International_dialing'=>'+592','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Haiti','country_code'=>'HT','International_dialing'=>'+509','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Heard Island and McDonald Islands (Territory of Australia)','country_code'=>'HM','International_dialing'=>'+x','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Holy See (Vatican City State)','country_code'=>'VA','International_dialing'=>'+x','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Honduras','country_code'=>'HN','International_dialing'=>'+504','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Hong Kong','country_code'=>'HK','International_dialing'=>'+852','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Hungary','country_code'=>'HU','International_dialing'=>'+36','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Iceland','country_code'=>'IS','International_dialing'=>'+354','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'India','country_code'=>'IN','International_dialing'=>'+91','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Indonesia','country_code'=>'ID','International_dialing'=>'+62','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Iran, Islamic Republic of','country_code'=>'IR','International_dialing'=>'+98','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Iraq','country_code'=>'IQ','International_dialing'=>'+964','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Ireland','country_code'=>'IE','International_dialing'=>'+353','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Israel','country_code'=>'IL','International_dialing'=>'+972','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Italy','country_code'=>'IT','International_dialing'=>'+39','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Jamaica','country_code'=>'JM','International_dialing'=>'+1-876','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Japan','country_code'=>'JP','International_dialing'=>'+81','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Jordan','country_code'=>'JO','International_dialing'=>'+962','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Kazakstands','country_code'=>'KZ','International_dialing'=>'+7','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Kenya','country_code'=>'KE','International_dialing'=>'+254','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Kiribati','country_code'=>'KI','International_dialing'=>'+686','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Korea, Democratic People\'s Republic of (North Korea)','country_code'=>'KP','International_dialing'=>'+850','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Korea, Republic of (South Korea)','country_code'=>'KR','International_dialing'=>'+82','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Kuwait','country_code'=>'KW','International_dialing'=>'+965','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Kyrgyzstan (Kyrgyz Republic) (Former Kirghiz Soviet Socialist Republic)','country_code'=>'KG','International_dialing'=>'+996','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Lao People\'s Democratic Republic (Laos)','country_code'=>'LA','International_dialing'=>'+856','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Latvia','country_code'=>'LV','International_dialing'=>'+371','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Lebanon','country_code'=>'LB','International_dialing'=>'+961','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Lesotho','country_code'=>'LS','International_dialing'=>'+266','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Liberia','country_code'=>'LR','International_dialing'=>'+231','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Libya (Libyan Arab Jamahiriya)','country_code'=>'LY','International_dialing'=>'+218','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Liechtenstein','country_code'=>'LI','International_dialing'=>'+423','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Lithuania (Former Lithuanian Soviet Socialist Republic)','country_code'=>'LT','International_dialing'=>'+370','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Luxembourg','country_code'=>'LU','International_dialing'=>'+352','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Macau','country_code'=>'MO','International_dialing'=>'+853','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Macedonia, The Former Yugoslav Republic of','country_code'=>'MK','International_dialing'=>'+389','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Madagascar','country_code'=>'MG','International_dialing'=>'+261','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Malawi','country_code'=>'MW','International_dialing'=>'+265','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Malaysia','country_code'=>'MY','International_dialing'=>'+60','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Maldives','country_code'=>'MV','International_dialing'=>'+960','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Mali','country_code'=>'ML','International_dialing'=>'+223','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Malta','country_code'=>'MT','International_dialing'=>'+356','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Marshall Islands','country_code'=>'MH','International_dialing'=>'+692','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Martinique','country_code'=>'MQ','International_dialing'=>'+596','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Mauritania','country_code'=>'MR','International_dialing'=>'+222','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Mauritius','country_code'=>'MU','International_dialing'=>'+230','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Mayotte','country_code'=>'YT','International_dialing'=>'+269','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Mexico','country_code'=>'MX','International_dialing'=>'+52','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Micronesia','country_code'=>'FM','International_dialing'=>'+691','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Moldova, Republic of','country_code'=>'MD','International_dialing'=>'+373','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Monaco, Principality of','country_code'=>'MC','International_dialing'=>'+377','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Mongolia','country_code'=>'MN','International_dialing'=>'+976','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Montserrat','country_code'=>'MS','International_dialing'=>'+1-664','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Morocco','country_code'=>'MA','International_dialing'=>'+212','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Mozambique (Former Portuguese East Africa)','country_code'=>'MZ','International_dialing'=>'+258','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Myanmar, Union of (Former Burma)','country_code'=>'MM','International_dialing'=>'+95','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Namibia','country_code'=>'NA','International_dialing'=>'+264','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Nauru','country_code'=>'NR','International_dialing'=>'+674','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Nepal','country_code'=>'NP','International_dialing'=>'+977','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Netherlands','country_code'=>'NL','International_dialing'=>'+31','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Netherlands Antilles','country_code'=>'AN','International_dialing'=>'+599','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'New Caledonia','country_code'=>'NC','International_dialing'=>'+687','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'New Zealand (Aotearoa)','country_code'=>'NZ','International_dialing'=>'+64','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Nicaragua','country_code'=>'NI','International_dialing'=>'+505','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Niger','country_code'=>'NE','International_dialing'=>'+227','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Nigeria','country_code'=>'NG','International_dialing'=>'+234','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Niue','country_code'=>'NU','International_dialing'=>'+683','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Norfolk Island','country_code'=>'NF','International_dialing'=>'+672','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Northern Mariana Islands ','country_code'=>'MP','International_dialing'=>'+1-670','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Norway','country_code'=>'NO','International_dialing'=>'+47','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Oman, Sultanate of (Former Muscat and Oman)','country_code'=>'OM','International_dialing'=>'+968','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Pakistan (Former West Pakistan)','country_code'=>'PK','International_dialing'=>'+92','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Palau','country_code'=>'PW','International_dialing'=>'+680','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Palestinian State (Proposed)','country_code'=>'PS','International_dialing'=>'+970','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Panama','country_code'=>'PA','International_dialing'=>'+507','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Papua New Guinea (Former Territory of Papua and New Guinea)','country_code'=>'PG','International_dialing'=>'+675','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Paraguay','country_code'=>'PY','International_dialing'=>'+595','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Peru','country_code'=>'PE','International_dialing'=>'+51','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Philippines','country_code'=>'PH','International_dialing'=>'+63','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Pitcairn Island','country_code'=>'PN','International_dialing'=>'+x','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Poland','country_code'=>'PL','International_dialing'=>'+48','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Portugal','country_code'=>'PT','International_dialing'=>'+351','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Puerto Rico','country_code'=>'PR','International_dialing'=>'+1-787 or +1-939','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Qatar, State of','country_code'=>'QA','International_dialing'=>'+974 ','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Reunion (French) (Former Bourbon Island)','country_code'=>'RE','International_dialing'=>'+262','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Romania','country_code'=>'RO','International_dialing'=>'+40','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Russia','country_code'=>'SU','International_dialing'=>'+x','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Russian Federation','country_code'=>'RU','International_dialing'=>'+7','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Rwanda','country_code'=>'RW','International_dialing'=>'+250','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Saint Helena','country_code'=>'SH','International_dialing'=>'+290','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Saint Kitts and Nevis','country_code'=>'KN','International_dialing'=>'+1-869','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Saint Lucia','country_code'=>'LC','International_dialing'=>'+1-758','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Saint Pierre and Miquelon','country_code'=>'PM','International_dialing'=>'+508','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Saint Vincent and the Grenadines','country_code'=>'VC','International_dialing'=>'+1-784','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Samoa','country_code'=>'WS','International_dialing'=>'+685','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'San Marino','country_code'=>'SM','International_dialing'=>'+378','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Sao Tome and Principe','country_code'=>'ST','International_dialing'=>'+239','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Saudi Arabia','country_code'=>'SA','International_dialing'=>'+966','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Serbia, Republic of','country_code'=>'RS','International_dialing'=>'+x','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Senegal','country_code'=>'SN','International_dialing'=>'+221','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Seychelles','country_code'=>'SC','International_dialing'=>'+248','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Sierra Leone','country_code'=>'SL','International_dialing'=>'+232','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Singapore','country_code'=>'SG','International_dialing'=>'+65','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Slovakia','country_code'=>'SK','International_dialing'=>'+421','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Slovenia','country_code'=>'SI','International_dialing'=>'+386','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Solomon Islands','country_code'=>'SB','International_dialing'=>'+677','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Somalia','country_code'=>'SO','International_dialing'=>'+252','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'South Africa (Former Union of South Africa)','country_code'=>'ZA','International_dialing'=>'+27','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'South Georgia and the South Sandwich Islands','country_code'=>'GS','International_dialing'=>'+x','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Spain','country_code'=>'ES','International_dialing'=>'+34','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Sri Lanka (Former Serendib, Ceylon)','country_code'=>'LK','International_dialing'=>'+94','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Sudan (Former Anglo-Egyptian Sudan)','country_code'=>'SD','International_dialing'=>'+249','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Suriname (Former Netherlands Guiana, Dutch Guiana)','country_code'=>'SR','International_dialing'=>'+597','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Svalbard (Spitzbergen) and Jan Mayen Islands','country_code'=>'SJ','International_dialing'=>'+x','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Swaziland, Kingdom of','country_code'=>'SZ','International_dialing'=>'+268','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Sweden','country_code'=>'SE','International_dialing'=>'+46','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Switzerland','country_code'=>'CH','International_dialing'=>'+41','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Syria (Syrian Arab Republic) (Former United Arab Republic - with Egypt)','country_code'=>'SY','International_dialing'=>'+963','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Taiwan','country_code'=>'TW','International_dialing'=>'+886','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Tajikistand','country_code'=>'TJ','International_dialing'=>'+992','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Tanzania, United Republic of (Former United Republic of Tanganyika and Zanzibar)','country_code'=>'TZ','International_dialing'=>'+255','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Thailand (Former Siam)','country_code'=>'TH','International_dialing'=>'+66','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Togo','country_code'=>'TG','International_dialing'=>'+x','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Tokelau','country_code'=>'TK','International_dialing'=>'+690','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Tonga, Kingdom of (Former Friendly Islands)','country_code'=>'TO','International_dialing'=>'+676','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Trinidad and Tobago','country_code'=>'TT','International_dialing'=>'+1-868','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Tromelin Island','country_code'=>'TE','International_dialing'=>'+x','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Tunisia','country_code'=>'TN','International_dialing'=>'+216','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Turkey','country_code'=>'TR','International_dialing'=>'+90','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Turkmenistan','country_code'=>'TM','International_dialing'=>'+993','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Turks and Caicos Islands','country_code'=>'TC','International_dialing'=>'+1-649','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Tuvalu','country_code'=>'TV','International_dialing'=>'+688','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Uganda, Republic of','country_code'=>'UG','International_dialing'=>'+256','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Ukraine','country_code'=>'UA','International_dialing'=>'+380','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'United Arab Emirates (UAE) (Former Trucial Oman, Trucial States)','country_code'=>'AE','International_dialing'=>'+971','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'United Kingdom (Great Britain / UK)','country_code'=>'GB','International_dialing'=>'+44','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'United States','country_code'=>'US','International_dialing'=>'+1','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'United States Minor Outlying Islands','country_code'=>'UM','International_dialing'=>'+x','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Uruguay, Oriental Republic of (Former Banda Oriental, Cisplatine Province)','country_code'=>'UY','International_dialing'=>'+598','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Uzbekistan','country_code'=>'UZ','International_dialing'=>'+998','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Vanuatu','country_code'=>'VU','International_dialing'=>'+678','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Vatican City State (Holy See)','country_code'=>'VA','International_dialing'=>'+418','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Venezuela','country_code'=>'VE','International_dialing'=>'+58','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Vietnam','country_code'=>'VN','International_dialing'=>'+84','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Virgin Islands, British','country_code'=>'VI','International_dialing'=>'+1-284','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Virgin Islands, United States (Former Danish West Indies)','country_code'=>'VQ','International_dialing'=>'+1-340','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Wallis and Futuna Islands','country_code'=>'WF','International_dialing'=>'+681','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Western Sahara (Former Spanish Sahara)','country_code'=>'EH','International_dialing'=>'+x','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Yemen','country_code'=>'YE','International_dialing'=>'+967','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Yugoslavia','country_code'=>'YU','International_dialing'=>'+x','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Zaire','country_code'=>'ZR','International_dialing'=>'+x','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Zambia, Republic of (Former Northern Rhodesia)','country_code'=>'ZM','International_dialing'=>'+260','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
        DB::table('countries')->insert( ['country_name'=>'Zimbabwe','country_code'=>'ZW','International_dialing'=>'+263','is_active'=>'1','created_at'=>now(),'updated_at'=>now()]);
       
    }
}
